---
title: "Email PoC"
author: "Travis Sondgerath"
date: "1/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,
                      message = F,
                      warning = F)
```

```{r}
library(ggplot2)
library(reader)
library(ggthemes)
library(knitr)
library(rmarkdown)
library(dplyr)
library(tidyr)
library(lubridate)
library(stringi)
library(stringr)
library(shiny)
library(shinyWidgets)
library(forcats)
library(readr)
library(readxl)
library(tibble)
library(kableExtra)

library(blastula)
# library(gt)
```

# Test Run

```{r}
# Created credentials to pass through emails, assuming I only have to create it once and reference it when I want to pass it - file now exists in the active WD

# create_email_creds_file(user = "pacafenet@gmail.com",
#                         password = "projectpi2018",
#                         provider = "gmail",
#                         sender = "Travis")
```

## Get Data

This is the same as the code I use to read into the application. 

```{r}
curr_date <- mdy("5/1/2016")

googlesheets::gs_auth(token = "shiny_app_token.rds")
my_sheets <- googlesheets::gs_ls()

sheet_key <- my_sheets$sheet_key[1]
ss <- googlesheets::gs_key(my_sheets$sheet_key[1])

# ss_data <- read_csv(file = "data\\fake_equip_data.csv") %>%
ss_data <- googlesheets::gs_read_csv(ss) %>%
  mutate(manufacture_date = mdy(manufacture_date),
         date_active = mdy(date_active),
         date_not_viable = mdy(date_not_viable),
         most_recent_calibration = mdy(most_recent_calibration),
         next_calibration = mdy(next_calibration),
         most_recent_maintenance = mdy(most_recent_maintenance),
         next_maintenance = mdy(next_maintenance),
         retirement_date = mdy(retirement_date),
         requires_attn = if_else(condition = date_not_viable < curr_date |
                                   next_calibration < curr_date |
                                   next_maintenance < curr_date,
                                 true = "red",
                                 false = if_else(condition = date_not_viable - curr_date < 10 |
                                                   next_calibration - curr_date < 10 |
                                                   next_maintenance - curr_date < 10,
                                                 true = "yellow",
                                                 false = "blue")),
         requires_attn_label = if_else(condition = date_not_viable < curr_date |
                                   next_calibration < curr_date |
                                   next_maintenance < curr_date,
                                 true = "Immediately",
                                 false = if_else(condition = date_not_viable - curr_date < 10 |
                                                   next_calibration - curr_date < 10 |
                                                   next_maintenance - curr_date < 10,
                                                 true = "Soon",
                                                 false = "OK")),
         viable_attn = if_else(condition = date_not_viable < curr_date,
                               true = 3,
                               false = if_else(condition = date_not_viable - curr_date < 10,
                                               true = 2,
                                               false = 1)),
         calibration_attn = if_else(condition = next_calibration < curr_date,
                               true = 3,
                               false = if_else(condition = next_calibration - curr_date < 10,
                                               true = 2,
                                               false = 1)),
         maintenance_attn = if_else(condition = next_maintenance < curr_date,
                               true = 3,
                               false = if_else(condition = next_maintenance - curr_date < 10,
                                               true = 2,
                                               false = 1)))
```

## Create the email to send to the maintenance engineer based on the current state of the data

```{r}

# Creates a call to action button
cta_button <- add_cta_button(url = "https://travis-shinin-spot.shinyapps.io/etool_dev/",
                             text = "eTool Link",
                             align = "center")

for(i in unique(ss_data$calib_engineer_nm)){
  
  # i <- unique(ss_data$calib_engineer_nm)[1]
  
  mail_dt <- ss_data %>% 
    filter(calib_engineer_nm == i &
             requires_attn %in% c("red", "yellow")) %>% 
    select(serial_num) 
  
  if(nrow(mail_dt) == 0){
    next
  }
  
  mail_dt <- mail_dt %>% 
    formattable::format_table()  # Replace with gt tables once I get the package working
  # gt::gt()
  
  email <- compose_email(body = paste0("Hello ",  # Use html tags for formatting - or md if I can get that package to work
                                       i, ", ", "<br>",
                                       "<br>",
                                       " The following serial numbers correspond to \\
                                       equipment that either requires attention now or will \\
                                       in the very near future. 
                                       <br>
                                       {mail_dt}<br>
                                       <br>
                                       Please click the link below to go to the eTool.<br>
                                       <br>
                                       {cta_button}<br>
                                       <br>
                                       Kind Regards,<br>
                                       <br>
                                       Travis Sondgerath, MS, MPH")) %>% 
      preview_email()  # Comment this part out once I'm ready to send a test email - needs to be an email object
  
  # Would need to add a lookup table like my progress reports for the correct emails
  
  send_email_out(message = email,
                 from = "pacafenet@gmail.com",
                 to = "tsondger@gmail.com",
                 subject = "Attn: Equipment Alert",
                 creds_file = ".bls_smtp_gmail_com")  # Think this is correct, although it looks a little weird - feel like there should be a file extension
  
}







```













