---
title: "eTool Dev Code"
author: "Travis Sondgerath"
date: "`r Sys.Date()`"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    source_code: embed
---

```{r global, include=FALSE}
knitr::opts_chunk$set(echo = F,
                      warning = F,
                      message = F)

library(dplyr)
library(shiny)
library(shinyWidgets)
library(sparkline)  # Make sure I need this package
library(DT)
library(tibble)
library(lubridate)
library(rmarkdown)
library(leaflet)
library(tidyr)
library(ggplot2)
library(stringr)

curr_date <- mdy("5/1/2016")

googlesheets::gs_auth(token = "shiny_app_token.rds")
my_sheets <- googlesheets::gs_ls()

sheet_key <- my_sheets$sheet_key[1]
ss <- googlesheets::gs_key(my_sheets$sheet_key[1])

# zz <- googlesheets::gs_read_csv(ss)
start_data <- googlesheets::gs_read_csv(ss) %>% 
  arrange(serial_num, desc(last_altered)) %>%
  distinct(serial_num, .keep_all = T)


start_1 <- start_data %>% 
  filter(str_detect(string = str_sub(str = manufacture_date, start = 1, end = 2), pattern = "20")) %>% 
  mutate(manufacture_date = ymd(manufacture_date),
         date_not_viable = ymd(date_not_viable),
         most_recent_calibration = ymd(most_recent_calibration),
         next_calibration = ymd(next_calibration),
         most_recent_maintenance = ymd(most_recent_maintenance),
         next_maintenance = ymd(next_maintenance),
         retirement_date = ymd(retirement_date),
         retirement_dt_requested = ymd_hms(retirement_dt_requested))

start_2 <- start_data %>% 
  filter(str_detect(string = str_sub(str = manufacture_date, start = 1, end = 2), pattern = "[^20]")) %>% 
  mutate(manufacture_date = mdy(manufacture_date),
         date_not_viable = mdy(date_not_viable),
         most_recent_calibration = mdy(most_recent_calibration),
         next_calibration = mdy(next_calibration),
         most_recent_maintenance = mdy(most_recent_maintenance),
         next_maintenance = mdy(next_maintenance),
         retirement_date = mdy(retirement_date),
         retirement_dt_requested = ymd_hms(retirement_dt_requested))

ss_data <- bind_rows(start_1, start_2) %>% 
  mutate(requires_attn = if_else(condition = (date_not_viable < curr_date |
                                   next_calibration < curr_date |
                                   next_maintenance < curr_date) &
                                   is.na(retirement_requested),
                                 true = "red",
                                 false = if_else(condition = (date_not_viable - curr_date < 10 |
                                                   next_calibration - curr_date < 10 |
                                                   next_maintenance - curr_date < 10) &
                                                   is.na(retirement_requested),
                                                 true = "yellow",
                                                 false = if_else(condition = !is.na(retirement_requested),
                                                                 true = "blue",
                                                                 false = "blue"))),
         requires_attn_label = if_else(condition = date_not_viable < curr_date |
                                   next_calibration < curr_date |
                                   next_maintenance < curr_date,
                                 true = "Immediately",
                                 false = if_else(condition = date_not_viable - curr_date < 10 |
                                                   next_calibration - curr_date < 10 |
                                                   next_maintenance - curr_date < 10,
                                                 true = "Soon",
                                                 false = "OK")),
         viable_attn = if_else(condition = date_not_viable < curr_date,
                               true = 3,
                               false = if_else(condition = date_not_viable - curr_date < 10,
                                               true = 2,
                                               false = 1)),
         calibration_attn = if_else(condition = next_calibration < curr_date,
                               true = 3,
                               false = if_else(condition = next_calibration - curr_date < 10,
                                               true = 2,
                                               false = 1)),
         maintenance_attn = if_else(condition = next_maintenance < curr_date,
                               true = 3,
                               false = if_else(condition = next_maintenance - curr_date < 10,
                                               true = 2,
                                               false = 1)))

# xx <- ss_data %>% filter(serial_num == 1277)
```

Inputs {.sidebar data-width=350}
-------------------------------------

```{r}

checkboxGroupInput(inputId = "attn_level",
            label = "Choose Facilities with Equip Requiring Attention:",
            choices = as.character(unique(ss_data$requires_attn_label)),
            selected = "Immediately",
            inline = T)

checkboxGroupInput(inputId = "lab_select",
            label = "Choose a Facility:",
            choices = as.character(unique(ss_data$facility)),
            selected = as.character(unique(ss_data$facility)),
            inline = T)

numericInput(inputId = "equip_select",
             label = "Select a Piece of Equipment to Edit Data:",
             value = min(ss_data$serial_num),
             min = min(ss_data$serial_num),
             max = max(ss_data$serial_num))

pickerInput(inputId = "column_edit",
            label = "Select a Date to Edit",
            choices = c("Most Recent Calibration" = "most_recent_calibration",
                        "Most Recent Maintenance" = "most_recent_maintenance"),
            selected = c("Most Recent Calibration" = "most_recent_calibration"),
            multiple = F)

dateInput(inputId = "dt_alteration",
          label = "Select a new date:",
          value = Sys.Date(),
          min = "2019-01-01")

actionBttn(inputId = "alter_dt_button",
           label = "Alter Date",
           style = "pill")

br()
br()

actionBttn(inputId = "retirement_button",
           label = "Submit Retirement Request",
           style = "pill")

values <- reactiveValues()

observe({
  input$alter_dt_button
  
  values$equip_id <- input$equip_select
})

observe({
  input$alter_dt_button
  
  values$dt_col <- input$column_edit
})

observe({
  input$alter_dt_button
  
  values$new_dt <- input$dt_alteration
})

observe({
  input$retirement_button
  
  values$retirement_flag <- 1
  
})

retire_update <- eventReactive(input$retirement_button,
                               {
                                 tt <- ss_data %>% 
                                   filter(serial_num == values$equip_id) %>% 
                                   mutate(retirement_requested = 1,
                                          last_altered = ymd_hms(Sys.time()),
                                          retirement_dt_requested = ymd_hms(Sys.time())) 
                               })

observeEvent(input$retirement_button,
             {
               googlesheets::gs_auth(token = "shiny_app_token.rds")
               my_sheets <- googlesheets::gs_ls()

               sheet_key <- my_sheets$sheet_key[1]
               ss <- googlesheets::gs_key(my_sheets$sheet_key[1])

               googlesheets::gs_add_row(ss = ss,
                                        input = retire_update())
             })

dt_update <- eventReactive(input$alter_dt_button,
                           {
                             tt <- ss_data %>%
                               filter(serial_num == values$equip_id) %>%
                               mutate(
                                 most_recent_maintenance = if_else(
                                   condition = values$dt_col == "most_recent_maintenance",
                                     true = values$new_dt,
                                     false = most_recent_maintenance
                                 ),
                                 most_recent_calibration = if_else(
                                   condition = values$dt_col == "most_recent_calibration",
                                   true = values$new_dt,
                                   false = most_recent_maintenance
                                 )
                               ) %>%
                               mutate(
                                 next_maintenance = if_else(
                                   condition = values$dt_col == "most_recent_maintenance",
                                   true = most_recent_maintenance + 90,
                                   false = next_maintenance
                                 ),
                                 next_calibration = if_else(
                                   condition = values$dt_col == "most_recent_calibration",
                                   true = most_recent_calibration + 180,
                                   false = next_calibration
                                 ),
                                 last_altered = ymd_hms(Sys.time())#,
                                 
                                 # most_recent_maintenance = paste(
                                 #   month(most_recent_maintenance),
                                 #   day(most_recent_maintenance),
                                 #   year(most_recent_maintenance),
                                 #   sep = "/"
                                 # ),
                                 # most_recent_calibration = paste(
                                 #   month(most_recent_calibration),
                                 #   day(most_recent_calibration),
                                 #   year(most_recent_calibration),
                                 #   sep = "/"
                                 # ),
                                 # next_maintenance = paste(
                                 #   month(next_maintenance),
                                 #   day(next_maintenance),
                                 #   year(next_maintenance),
                                 #   sep = "/"
                                 # ),
                                 # next_calibration = paste(
                                 #   month(next_calibration),
                                 #   day(next_calibration),
                                 #   year(next_calibration),
                                 #   sep = "/"
                                 # )#,
                                 # last_altered = paste(month(last_altered), day(last_altered), year(last_altered), sep = "/")
                               )
                             
                           })

observeEvent(input$alter_dt_button,
             {
               googlesheets::gs_auth(token = "shiny_app_token.rds")
               my_sheets <- googlesheets::gs_ls()

               sheet_key <- my_sheets$sheet_key[1]
               ss <- googlesheets::gs_key(my_sheets$sheet_key[1])

               googlesheets::gs_add_row(ss = ss,
                                        input = dt_update())
             })

```

Row 1 {.tabset .tabset-fade data-height=800}
-----------------------------------------------------------------------

### Situation Map {.no-mobile}

```{r eval=FALSE}
# renderPrint(
# renderText(
  # ymd(values$new_dt)
DT::renderDataTable(
  dt_update()
)
```


```{r}

renderLeaflet({

plot1 <- ss_data %>% 
  group_by(facility, lat, long, requires_attn_label) %>% 
  tally() %>% 
  spread(key = requires_attn_label, value = n) %>%
  ungroup() %>%
  mutate(requires_attn_label = if_else(condition = Immediately > 0,
                                 true = "Immediately",
                                 false = if_else(Soon > 0,
                                                 true = "Soon",
                                                 false = "OK")),
         requires_attn_color = if_else(condition = requires_attn_label == "Immediately",
                                   true = "red",
                                   false = if_else(condition = requires_attn_label == "Soon",
                                                   true = "yellow",
                                                   false = "blue")),
         lat = jitter(lat, factor = 1),
         long = jitter(long, factor = 1)) %>%
  filter(requires_attn_label %in% c(input$attn_level)) %>%
  # filter(requires_attn == "red") %>%
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers(lng = ~long,
                   lat = ~lat,
                   popup = ~facility,
                   color = ~requires_attn_color,
                   fill = F)

plot1

})
```

### Edit Data

```{r}
renderDataTable({
  # tt <- 
  ss_data %>% 
    # filter(requires_attn_label == "Immediately") %>%
    filter(requires_attn_label %in% c(input$attn_level)) %>%
    filter(facility %in% c(input$lab_select)) %>%
    select(7, 1:2, 6, 12:15, 26:28) %>% 
    datatable(rownames = F,
              fillContainer = T,
              filter = "none",
              selection = "single",
              options = list(
    columnDefs = list(list(targets = c(8:10), visible = FALSE))
    )) %>% 
    formatStyle(columns = "date_not_viable",
                valueColumns = "viable_attn",
                backgroundColor = styleEqual(c(3, 2, 1), c("red", "yellow", "white")),
                color = styleEqual(c(3, 2, 1), c("white", "black", "black"))) %>% 
    formatStyle(columns = "next_calibration",
                valueColumns = "calibration_attn",
                backgroundColor = styleEqual(c(3, 2, 1), c("red", "yellow", "white")),
                color = styleEqual(c(3, 2, 1), c("white", "black", "black"))) %>%
    formatStyle(columns = "next_maintenance",
                valueColumns = "maintenance_attn",
                backgroundColor = styleEqual(c(3, 2, 1), c("red", "yellow", "white")))
  
  # NEED TO CREATE ANOTHER VARIABLE FOR EACH DATE IN THE SETUP THAT WILL GIVE THE BACKGROUND COLOR FOR EACH DATE (WHERE APPLICABLE) - HIDE THESE DUMMY COLUMNS USING THE COLUMNDEFS FUNCTION IN THE OPTIONS STATEMENT (SEE DT DOCS ABOUT BACKGROUND COLORS)
    # formatStyle("date_not_viable",
    #             backgroundColor = styleInterval(c(date)))
  
})
```


Row 2 {.tabset .tabset-fade}
-----------------------------------------------------------------------

### By Attention Category {.no-mobile}

```{r}

tt <- ss_data %>% 
  group_by(requires_attn_label) %>% 
  tally() 

plot2 <- tt %>% 
  ggplot(aes(x = requires_attn_label, weight = n, fill = requires_attn_label)) +
  geom_bar() +
  scale_fill_manual(values = c("red", "blue", "yellow")) +
  scale_y_continuous(limits = c(0, 10000), breaks = seq(0, 10000, 1000)) +
  theme_classic() +
  theme(legend.position = "none",
        axis.title = element_blank(),
        axis.text.x = element_text(face = "bold"),
        axis.text.y = element_text(face = "bold"))

# tt

p1 <- plotly::ggplotly(plot2)

p1

kableExtra::kable_styling(knitr::kable(tt))

```

### By Facility {.no-mobile}

```{r}
# Number requiring immediate attention by facility

tt2 <- ss_data %>% 
  filter(requires_attn_label == "Immediately") %>% 
  group_by(facility) %>% 
  tally()

plot3 <- tt2 %>% 
  ggplot(aes(x = facility, weight = n)) +
  geom_bar(fill = "white", color = "black") +
  # scale_y_continuous(limits = c(0, 10000), breaks = seq(0, 5000, 500)) +
  theme_classic() +
  theme(legend.position = "none",
        axis.title = element_blank(),
        axis.text.x = element_text(face = "bold"),
        axis.text.y = element_text(face = "bold"))

p2 <- plotly::ggplotly(plot3)

p2

# tt2

kableExtra::kable_styling(knitr::kable(tt2))

```

### By Lab Level {.no-mobile}

```{r}
# Number requiring attention by level

tt3 <- ss_data %>% 
  filter(requires_attn_label == "Immediately") %>% 
  group_by(lab_level) %>% 
  tally()

plot4 <- tt3 %>% 
  ggplot(aes(x = lab_level, weight = n)) +
  geom_bar(fill = "white", color = "black") +
  # scale_y_continuous(limits = c(0, 10000), breaks = seq(0, 5000, 500)) +
  theme_classic() +
  scale_x_discrete(limits = c("district", "regional", "national", "other")) +
  ggtitle("Equipment Requiring Immediate Attention") +
  theme(legend.position = "none",
        axis.title = element_blank(),
        axis.text.x = element_text(face = "bold"),
        axis.text.y = element_text(face = "bold"))

# tt3

p4 <- plotly::ggplotly(plot4)

p4

kableExtra::kable_styling(knitr::kable(tt3))

```










