---
title: "Creating Fake Equipment Data"
output: html_document
author: Travis Sondgerath
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = T,
                      warning = F,
                      message = F)

library(ggplot2)
library(reader)
library(ggthemes)
library(knitr)
library(rmarkdown)
library(dplyr)
library(tidyr)
library(lubridate)
library(stringi)
library(shiny)
library(shinyWidgets)
library(forcats)
library(readr)
library(tibble)

```

```{r}

set.seed(12345)

df <- tibble(serial_num = 1:10000) %>% 
  rowwise() %>%
  mutate(equip_type = sample(c("hiv reagents",
                         "CD4_CD8_counter",
                         "pcr_machine",
                         "P24",
                         "spectrophotometer",
                         "coulter",
                         "centrifuge",
                         "micropipettes",
                         "pcr_tube",
                         "graduated_pipettes"),
                       size = 1,
                       replace = T),
         manufacturer = sample(c("lab_equip_r_us",
                          "best_labs",
                          "quality_equip"),
                        size = 1,
                        replace = T,
                        prob = c(.5, .25, .25)),
          manufacture_date = sample(seq(mdy("1/1/2016"), mdy("12/31/2017"), by = "day"),
                            size = 1,
                            replace = T),
         date_active = manufacture_date + sample(1:30,
                                                 size = 1,
                                                 replace = T),
         date_not_viable = manufacture_date + 730,
         facility = sample(c("Lab1",
                             "Lab2",
                             "Lab3",
                             "Lab4",
                             "Lab"),
                           size = 1,
                           replace = T),
         ownership_type = sample(c("gov",
                                 "private",
                                 "parochial"),
                                 size = 1,
                                 replace = T,
                                 prob = c(.75, .2, .05)),
         lab_level = sample(c("national",
                              "regional",
                              "district",
                              "other"),
                            size = 1,
                            replace = T,
                            prob = c(.05, .25, .6, .1)),
         calib_engineer_nm = sample(c("tech1",
                                "tech2",
                                "tech3"),
                              size = 1,
                              replace = T),
         calib_engineer_post = ifelse(test = calib_engineer_nm == "tech1",
                                yes = "affiliate1",
                                no = ifelse(test = calib_engineer_nm == "tech2",
                                            yes = "affiliate2",
                                            no = "affiliate3")),
         most_recent_calibration = date_active + sample(1:60,
                                                        size = 1,
                                                        replace = T),
         next_calibration = most_recent_calibration + 90,
         most_recent_maintenance = date_active + sample(30:90,
                                                        size = 1,
                                                        replace = T),
         next_maintenance = most_recent_maintenance + 180,
         maintenance_engineer_nm = sample(c("tech1",
                                            "tech2",
                                            "tech3"),
                                          size = 1,
                                          replace = T),
         maintenance_engineer_post = ifelse(test = maintenance_engineer_nm == "tech1",
                                yes = "affiliate1",
                                no = ifelse(test = maintenance_engineer_nm == "tech2",
                                            yes = "affiliate2",
                                            no = "affiliate3")),
         retirement_date = date_active + 720,
         retirement_requested = "",
         retirement_dt_requested = "",
         long = ifelse(test = facility == "Lab",
                       yes = 11.502075200000036,
                       no = ifelse(test = facility == "Lab1",
                                   yes = 9.767868700000008,
                                   no = 3.379205700000057)),
         lat = ifelse(test = facility == "Lab",
                       yes = 3.848032500000001,
                       no = ifelse(test = facility == "Lab1",
                                   yes = 4.0510564,
                                   no = 6.5243793)),
         last_altered = mdy_hms("1/1/2016 00:00:01"))
  

# equip types - http://cies.edu.ni/cedoc/general/World%20Health%20Organization%20HIV-AI%20(D)2/pdfs/list-laboratory.pdf


# Equipment location GPS coordinates

```

```{r eval=FALSE}
write_csv(df,
          path = "data\\fake_equip_data.csv")

```






























