---
title: "scratchpad"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      warning = F,
                      message = F)

library(dplyr)
library(plyr)
library(shiny)
library(shinyWidgets)
library(sparkline)
library(DT)
library(tibble)
library(stringr)
library(RCurl)
library(rjson)
library(lubridate)
library(tibble)
library(readr)

```

## Sparklines in a Data Table

```{r}
data(iris)
```

```{r}

selectInput("species",
            label = "Select a flower species",
            choices = as.character(unique(iris$Species)),
            selected = as.character(unique(iris$Species[1])))

```


```{r}

# tt <- eventReactive(input$species,
#                     {
#                       iris %>% 
#                         filter(Species == "setosa")
#                     })

# tt_sparkdata <- iris %>% 
#   filter(Species == "setosa")

# tt <- sparkline(tt_sparkdata[[1]])



# tt
# xx

```

This is a test

```{r}

renderSparkline({
  tt_sparkdata <- iris %>%
    filter(Species == input$species)
    # filter(Species == "versicolor")
  
  sparkline(tt_sparkdata[[1]])
})

```

to see if I can fake a table

```{r}

renderSparkline({
  tt_sparkdata <- iris %>%
    filter(Species == input$species)
  
  sparkline(tt_sparkdata[[2]])
})

```

```{r}
# Other example below in comments

# spk_data <- nhsn_events %>% 
#   select(1, 3:6) %>% 
#   inner_join(x = ., 
#              y = tt <- nhsn_events %>% filter(collab_assign == "selected"), 
#              by = "CO_ID") %>% 
#   arrange(HOSP_NAME.x) %>% 
#   select(2:5) %>% 
#   t() %>% 
#   as_tibble()

# nhsn_events_collab <- nhsn_events %>% 
#   filter(collab_assign == "selected") %>% 
#   arrange(HOSP_NAME.x)
# 
# colnames(spk_data) <- sort(nhsn_events$HOSP_NAME.x[nhsn_events$collab_assign == "selected"])

# spk_chr(spk_data[[2]], min = 0, max = 200),

renderDataTable({
  tt_sparkdata <- iris %>%
    filter(Species == input$species)
  
  tt_table <- tibble(
    spark_names = c("test1", "test2"),
    spark_test = c(spk_chr(tt_sparkdata[[1]]), spk_chr(tt_sparkdata[[2]]))
  ) %>% 
    datatable(escape = F,
              rownames = F,
              options = list(fnDrawCallback = htmlwidgets::JS('function(){
                                                              HTMLWidgets.staticRender();
                                                              }'),
                             searching = F)) %>% 
    spk_add_deps()
  
})
```

## Google sheets authentication

```{r}

# Global.R that I'll need to keep with my app

library(googlesheets)  # May just want to call these explicitly from the package

## prepare the OAuth token and set up the target sheet:
##  - do this interactively
##  - do this EXACTLY ONCE

# shiny_token <- gs_auth() # authenticate w/ your desired Google identity here
# saveRDS(shiny_token, "shiny_app_token.rds")

gs_auth(token = "shiny_app_token.rds")  # Use henceforth
my_sheets <- gs_ls()

sheet_key <- my_sheets$sheet_key[1]  # Fake data key, refer to a different key for other data
ss <- gs_key(sheet_key)  # Defines the sheet I want to interact with

# Reading the data as it is currently, this is what I'll want to refer to in the server function

ss_data <- gs_read_csv(ss)  # Pulls the data as a df, may need to manipulate the data types, but can worry about that later
```

## Reading in ONA Data

```{r}

## Think it might only work for open projects. 

file_data <- read_csv(file = "https://ona.io/pacafenet/99874/459644/download.csv?data-type=dataset")  ## Enter new equipment form 

```

## Using purrr instead of rowwise()

```{r}
library(purrr)

tt <- zz %>% 
  select(1, 4) %>% 
  map_if(str_detect(string = str_sub(str = .$manufacture_date, start = 1, end = 2), 
                    pattern = "20"), 
         ymd) %>%
  # map_at("manufacture_date", mdy) %>% ## By column name
  # map_at(2, mdy) %>%   # By position
  as_tibble()

curr_date <- mdy("5/1/2016")

googlesheets::gs_auth(token = "shiny_app_token.rds")
my_sheets <- googlesheets::gs_ls()

sheet_key <- my_sheets$sheet_key[1]
ss <- googlesheets::gs_key(my_sheets$sheet_key[1])

zz <- googlesheets::gs_read_csv(ss)

# Sad face

tt1 <- zz %>% 
  select(1, 4) %>% 
  map_at(2, if_else(condition = str_detect(string = str_sub(str = .$manufacture_date, start = 1, end = 2), pattern = "20"),
                    true = ymd,
                    false = mdy) %>% 
  as_tibble()

```





